apiVersion: v1
kind: Secret
metadata:
  name: guacamole-wrapper-secret
  labels:
    app: guacamole-wrapper

type: Opaque
stringData:
  DB_DIALECT: "postgresql+asyncpg"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "wrapper_db"
  DB_USER: "guacadmin"
  DB_PASSWORD: "password"
  GUACAMOLE_USERNAME: "guacadmin"
  GUACAMOLE_PASSWORD: "changeme"
  GUACAMOLE_NEW_USER_PASSWORD: "changeme"
  GUACAMOLE_SSH_PASSWORD: "changeme"
