apiVersion: v1
kind: Service
metadata:
  name: guacamole-wrapper
  labels:
    app: guacamole-wrapper

spec:
  type: ClusterIP
  selector:
    app: guacamole-wrapper
  ports:
    - name: http
      port: 8000
      targetPort: http
