"""Add guacamole_group_id to workspaces

Revision ID: 96fc54a275bf
Revises: af06a77b7551
Create Date: 2026-05-02 21:30:19.574330
"""

from alembic import op
import sqlalchemy as sa


revision = '96fc54a275bf'
down_revision = 'af06a77b7551'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
