"""Add guacamole_group_id to workspaces

Revision ID: af06a77b7551
Revises: 20260501_0002_os_creds
Create Date: 2026-05-02 21:30:06.131044
"""

from alembic import op
import sqlalchemy as sa


revision = 'af06a77b7551'
down_revision = '20260501_0002_os_creds'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('guacamole_group_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'guacamole_group_id')
    # ### end Alembic commands ###
