"""describe change

Revision ID: eeccc3f9ab2f
Revises: 20260501_000001
Create Date: 2026-05-01 17:12:43.809537
"""

from alembic import op
import sqlalchemy as sa


revision = 'eeccc3f9ab2f'
down_revision = '20260501_000001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('external_user_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('external_user_id'),
    sa.UniqueConstraint('username')
    )
    op.drop_constraint(op.f('workspaces_external_instance_id_key'), 'workspaces', type_='unique')
    op.create_foreign_key(None, 'workspaces', 'users', ['user_id'], ['external_user_id'], ondelete='CASCADE')
    op.drop_column('workspaces', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.create_unique_constraint(op.f('workspaces_external_instance_id_key'), 'workspaces', ['external_instance_id'], postgresql_nulls_not_distinct=False)
    op.drop_table('users')
    # ### end Alembic commands ###
